Added files to create a service on the Raspberry Pi
uorocketry/rocket-code-2020 pull request #125
Opened 2021-10-10 03:23 UTC by sebastiengrd

Useful to automatically run rocket code on startup. Needs to be updated in the future to restart if it crashes

2021-10-10 03:25 UTC, ajayyy approved these changes

2021-10-10 03:33 UTC, jonapap commented on control/service/rocket_startup.service
> +ExecStart=sudo /home/pi/rocket-code-2020/sbgECom/bin/MainLoop &
Are you sure this is the right path? Shouldn't this be under some build folder?

2021-10-30 17:01 UTC, ajayyy requested changes
We should take the changes to the service files from the pi for this one too @sebastiengrd

2021-11-09 03:29 UTC, ajayyy approved these changes

2021-11-13 18:32 UTC, jonapap approved these changes

2021-11-13 18:32 UTC, jonapap commented on CMakeLists.txt
> +	target_link_libraries(MainLoopLib systemd)
Heads up that this is another dynamically linked library, so no support for cross-compile

2021-11-28 19:14 UTC, ajayyy commented
@jonapap good to merge this as well?

2021-11-28 19:17 UTC, jonapap commented
> @jonapap good to merge this as well?

Yes, LGTM

2021-11-28 19:20 UTC, merged