Socket c++
uorocketry/rocket-code-2020 pull request #21
Opened 2020-08-22 19:55 UTC by sebastiengrd

Implement TCP connection with socket in c++

2020-09-12 19:39 UTC, ajayyy approved these changes

2020-09-12 20:00 UTC, ajayyy requested changes
Todo: Add environment variable behind this

2020-09-13 02:54 UTC, ajayyy approved these changes
Looks good to merge now. Can you quickly check over the changes I made before we merge it @sebastiengrd ?

2020-09-19 01:33 UTC, sebastiengrd commented
Yep look good to merge, I did some minor modifications for the switch bank and I added the if conditions at some places of the code for when we use the socket control.

2020-09-19 01:44 UTC, ajayyy approved these changes

2020-09-19 01:54 UTC, merged