add a servo control project to test the servos using hotfire configs
uorocketry/rocket-code-2020 pull request #58
Opened 2021-04-11 03:38 UTC by kovalromank

Added a ServoControl project which implements HotFire's states `ST_INIT`, `ST_WAIT_FOR_INIT`, `ST_WAIT_FOR_FILLING`, `ST_FILLING`, `ST_DONE` and `ST_ABORT_FILLING` to make it easier to test all the servos before the HotFire test.

The implementation of each state was just copied over, I couldn't find a way around just copying the code. This means that any changes to the HotFire state machine should be copied to the ServoControl state machine as well.

The new project just imports HotFire's `config.h` and `GpioConfig.h`. I'm not sure if we want that or if the ServoControl should have it's own configs.

2021-04-17 16:37 UTC, sebastiengrd commented
This state machine and the state machine of hotfire test shouldn't be the same. This one should be more simple, and what the project is supposed to do is open and close each of the 5 valves individually one at a time. It will be used to open/close each valves to test them. But it should open and close them with the configs files of the hotfire test

2021-04-24 18:25 UTC, ajayyy requested changes

2021-04-24 18:25 UTC, ajayyy commented on projects/ServoControl/config/UOStateMachine.cpp
> +#endif
Can you indent this?

2021-04-24 18:25 UTC, ajayyy commented on projects/ServoControl/config/UOStateMachine.cpp
> +#endif
Can you indent this

2021-04-24 18:38 UTC, ajayyy submitted a review, later dismissed

2021-04-24 18:39 UTC, ajayyy commented on CMakeLists.txt
> +endif()
```suggestion
if (DEFINED ENV{SERVO_CONTROL} OR SERVO_CONTROL)
	add_definitions(-D SERVO_CONTROL=$ENV{SERVO_CONTROL})
endif()
```

2021-04-24 18:43 UTC, ajayyy approved these changes

2021-04-24 18:44 UTC, merged