Add support for software PWM
uorocketry/rocket-code-2020 pull request #91
Opened 2021-05-30 15:42 UTC by jonapap

Fixes #89

2021-06-26 18:12 UTC, ajayyy commented on src/IO/gpio/PwmOutput.h
> +    PwmOutput(std::string name, int pin, bool softPWM = false);
Is there a reason this was changed?

2021-07-03 17:34 UTC, ajayyy requested changes

2021-07-03 17:34 UTC, ajayyy commented on projects/HotFire/config/GpioConfig.h
> +#endif
`#endif` are indented differently than `#if USE_SV02`

2021-07-03 17:34 UTC, ajayyy commented on src/IO/gpio/Gpio.h
> +class Gpio : public IO {
Revert this change

2021-07-03 17:34 UTC, ajayyy commented on src/IO/gpio/Gpio.h
> +	struct InitFlags {
Revert

2021-07-03 17:34 UTC, ajayyy commented on src/IO/gpio/PwmOutput.cpp
> +#endif
Newline curly brace

2021-07-03 17:34 UTC, ajayyy commented on src/IO/gpio/PwmOutput.cpp
> +    if (currentState != value) {
Newline curly brace

2021-07-10 17:48 UTC, jonapap commented on src/IO/gpio/PwmOutput.cpp
> +#endif
Wait, also for `if` statements?

2021-08-29 00:51 UTC, ajayyy commented
https://github.com/uorocketry/rocket-code-2020/pull/106

2021-09-20 20:01 UTC, closed without merging